###

name: Sophos XDR License Report

# Controls when the workflow will run
on:
  # Runs at 00:00 UTC every day
  schedule:
    - cron: '0 0 * * *'
  
  # Allows manual trigger from the Actions tab
  workflow_dispatch:

# Environment variables available to all jobs and steps
env:
  OUTPUT_FILE: sophos_license_report.csv

jobs:
  generate-report:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v3
      
      # Set up PowerShell on Ubuntu
      - name: Set up PowerShell
        uses: actions/setup-powershell@v2
        with:
          powershell-version: '7.2'
      
      # Run the PowerShell script with secrets
      - name: Run Sophos API script
        shell: pwsh
        env:
          SOPHOS_CLIENT_ID: ${{ secrets.SOPHOS_CLIENT_ID }}
          SOPHOS_CLIENT_SECRET: ${{ secrets.SOPHOS_CLIENT_SECRET }}
          SOPHOS_TENANT_ID: ${{ secrets.SOPHOS_TENANT_ID }}
        run: |
          ./scripts/get-sophos-licenses.ps1
      
      # Configure Git user
      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      
      # Commit and push if there are changes
      - name: Commit and push changes
        run: |
          git add ${{ env.OUTPUT_FILE }}
          git diff --staged --quiet || git commit -m "Update Sophos XDR license data [skip ci]"
          git push
