name: Sophos License Collector

on:
  schedule:
    - cron: '0 6 * * *'  # Runs at 6:00 AM UTC every day
  workflow_dispatch:  # Allows manual triggering

jobs:
  collect-license-data:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Run PowerShell script
      shell: pwsh
      env:
        SOPHOS_CLIENT_ID: ${{ secrets.SOPHOS_CLIENT_ID }}
        SOPHOS_CLIENT_SECRET: ${{ secrets.SOPHOS_CLIENT_SECRET }}
        SOPHOS_TENANT_ID: ${{ secrets.SOPHOS_TENANT_ID }}
      run: |
        ./scripts/get-sophos-licenses.ps1
    
    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add SophosLicenses.csv
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update Sophos license data - $(Get-Date -Format 'yyyy-MM-dd')" && git push)
        git remote set-url origin https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }}
        git push
        
