name: Sophos XDR License Report

on:
  schedule:
    - cron: '0 0 * * *'  # Every day at 00:00 UTC
  workflow_dispatch:

env:
  OUTPUT_FILE: output/sophos_license_report.csv

jobs:
  generate-report:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up PowerShell
      - name: Set up PowerShell
        uses: actions/setup-powershell@v1
        with:
          powershell-version: '7.2'

      # Step 3: Run the updated PowerShell script
      - name: Run Sophos API script
        shell: pwsh
        env:
          SOPHOS_CLIENT_ID: ${{ secrets.SOPHOS_CLIENT_ID }}
          SOPHOS_CLIENT_SECRET: ${{ secrets.SOPHOS_CLIENT_SECRET }}
          SOPHOS_TENANT_ID: ${{ secrets.SOPHOS_TENANT_ID }}
          OUTPUT_FILE: ${{ env.OUTPUT_FILE }}
        run: ./scripts/get-sophos-licenses.ps1

      # Step 4: Configure Git
      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      # Step 5: Commit and push only if changes exist
      - name: Commit and push changes
        run: |
          git add ${{ env.OUTPUT_FILE }}
          git diff --staged --quiet || git commit -m "Update Sophos XDR license data [skip ci]"
          git push
